version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sample_app_docker_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    tty: true
    stdin_open: true
    build: ../../
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ../../:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:secret@db:5432/sample_app_docker_development
      REDIS_URL: "redis://redis:6379/0"  # Add this line to specify the Redis URL for Rails

  redis:
    image: redis
    volumes:
      - ../../tmp/db:/var/lib/redis/data
  sidekiq:
    build: ../../
    command: 'bundle exec sidekiq'
    volumes:
      - ../../:/myapp
    environment:
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/0"
      DATABASE_URL: postgres://postgres:secret@db:5432/sample_app_docker_development
    depends_on:
      - redis
      - db

volumes:
  postgres_data: